### ISSUE TITLE
Project is not yet online

### ISSUE THREAD

**Issue by elvis-suazo** [elvis-suazo/food-website#3]
The old website is the one online, not this one. And yes, they do look the same, but, are different.

**Comment by Headshake** [comment]
> The old website is the one online, not this one. And yes, they do look the same, but, are different.

Working on it...

**Comment by elvis-suazo** [comment]
Another way of expressing what I want is: 

> deploy nodejs app

:)

**Comment by Headshake** [comment]
https://www.phusionpassenger.com/library/walkthroughs/deploy/nodejs/ownserver/nginx/oss/trusty/deploy_app.html

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

**Comment by elvis-suazo** [comment]
I fixed it.
